### ISSUE TITLE
Send site creator a DM on Twitter when there's a new submission

### ISSUE THREAD

**Issue by chrismytton** [mysociety/political_tweets#16]
When a new Twitter handle is submitted from a generated site we should notify the person who originally created the site for that country. Since we haven't got an email address for them, it seems like sending a Twitter DM could be a simple solution.

**Comment by chrismytton** [comment]
This will also require the user to follow [SeePoliticians](https://twitter.com/seepoliticians) on Twitter, as I think you can only DM someone if they are following you.

**Comment by dracos** [comment]
You can set in your options now to allow DMs from anyone.
