### ISSUE TITLE
Make Twitter handle display consistent on generated site

### ISSUE THREAD

**Issue by chrismytton** [mysociety/political_tweets#18]
Twitter handles are displayed inconsistently on the generated site. They should be correctly formatted as `@username`.

![screen shot 2015-08-27 at 10 40 29](https://cloud.githubusercontent.com/assets/22996/9517457/17414ac2-4ca8-11e5-876a-9ab75b8e2914.png)

**Comment by zarino** [comment]
Also, the hyperlinks currently just go to `#`.
