### ISSUE TITLE
Better handling of places with no twitter handles

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/political_tweets#23]
If no representatives have twitter handles we should give a better message.

Currently:

![screen shot 2015-08-27 at 12 34 49](https://cloud.githubusercontent.com/assets/57483/9519623/0ea6c030-4cb8-11e5-8336-aad7fcf1771e.png)

**Comment by zarino** [comment]
Since we can't alter the "Hmm, an empty timeline" message, we'll need to avoid rendering the twitter widget entirely in these cases (cases where there are no politicians with twitter handles in the specified area).

**Comment by zarino** [comment]
@tmtmtmtm – what would you like the "better message" to say?

**Comment by tmtmtmtm** [comment]
@zarino I think you misspelled @MyfanwyNixon there :)

**Comment by MyfanwyNixon** [comment]
If I've understood this scenario correctly:

> We don't know about any politicians who tweet in [area name]. Perhaps you can add some?

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon it's not about adding politicians — it's when we already know who the politicians are, but don't have any twitter handles for them.

**Comment by MyfanwyNixon** [comment]
Oh ok.

> We don't know the Twitter names for the politicians in this area . Perhaps you can help us find them?

**Comment by tmtmtmtm** [comment]
Yep, that works! 

We should probably rename that "Politicians not on Twitter" section too — it's for the ones where we don't know whether they are or aren't…

**Comment by zarino** [comment]
Pull request (with clear message when there are no tweeters in an area) here: https://github.com/mysociety/SeePoliticiansTweet/pull/77
