### ISSUE TITLE
What should happen if the GitHub repo for a site is deleted?

### ISSUE THREAD

**Issue by chrismytton** [mysociety/political_tweets#27]
We should probably detect this somehow and automatically disable the site until the user regenerates it? Perhaps send them a DM on Twitter when we detect it?

**Comment by tmtmtmtm** [comment]
If this happens it's probably something that _we_ should look at, rather than the user…

**Comment by chrismytton** [comment]
Closing this, it's going to be such a rare occurrence that we can manually intervene if necessary.
