### ISSUE TITLE
Stop using old countries.json

### ISSUE THREAD

**Issue by chrismytton** [mysociety/political_tweets#4]
We're currently using http://data.everypolitician.org/countries.json to get the latest term CSV, but that file has been superseded by https://github.com/everypolitician/everypolitician-data/blob/master/countries.json. We should switch to using that file and calculate the current legislative session by checking for a `latest: true` flag on a legislative session.

**Comment by tmtmtmtm** [comment]
depends on https://github.com/everypolitician/everypolitician-data/issues/254

**Comment by chrismytton** [comment]
Will also need to deal with legislatures which were introduced in https://github.com/everypolitician/everypolitician-data/pull/258.

**Comment by tmtmtmtm** [comment]
The legislative periods are now listed in reverse chronological order, so you can just take the first one as the latest.
