### ISSUE TITLE
Difficult to scroll people list on wide screens

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/political_tweets#40]
When there are a lot of politicians, it's difficult to scroll the list of them as there's no visual distinction between the column they're actually in (where you need to scroll) and the un-scrollable column to the right of it

![screen shot 2015-09-03 at 17 00 32](https://cloud.githubusercontent.com/assets/57483/9663672/7bcc8b54-525d-11e5-8dd0-d4fed4822f49.png)

http://seepoliticianstweet.github.io/Estonia_Riigikogu/areas/tallinna-mustam-e-ja-n-mm.html

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/SeePoliticiansTweet/pull/79
